Level_1 = [
    ["Which Indian state is known as the 'Land of Five Rivers'?", "A Punjab", "B Haryana", "C Rajasthan", "D Gujarat", "A", "Punjab"],
    ["Who was the first woman Prime Minister of India?", "A Indira Gandhi", "B Sarojini Naidu", "C Pratibha Patil", "D Sushma Swaraj", "A", "Indira Gandhi"],
    ["Which river is called the 'Sorrow of Bihar'?", "A Kosi", "B Ganga", "C Yamuna", "D Brahmaputra", "A", "Kosi"],
    ["What is the national flower of India?", "A Rose", "B Lotus", "C Marigold", "D Jasmine", "B", "Lotus"],
    ["Which Indian city is known as 'City of Joy'?", "A Mumbai", "B Kolkata", "C Chennai", "D Hyderabad", "B", "Kolkata"],
    ["In which year did India gain independence?", "A 1945", "B 1947", "C 1950", "D 1942", "B", "1947"],
    ["Which is the smallest state in India by area?", "A Goa", "B Sikkim", "C Tripura", "D Nagaland", "A", "Goa"],
    ["Which metal is liquid at room temperature?", "A Mercury", "B Iron", "C Gold", "D Aluminium", "A", "Mercury"],
    ["What is the boiling point of water in Celsius?", "A 90", "B 100", "C 110", "D 120", "B", "100"],
    ["Which planet is closest to the Sun?", "A Venus", "B Mercury", "C Mars", "D Earth", "B", "Mercury"],
    ["Who invented the telephone?", "A Thomas Edison", "B Alexander Graham Bell", "C Nikola Tesla", "D Isaac Newton", "B", "Alexander Graham Bell"],
    ["What is the chemical formula of table salt?", "A NaCl", "B H2SO4", "C CO2", "D NaOH", "A", "NaCl"],
    ["Which instrument measures atmospheric pressure?", "A Thermometer", "B Barometer", "C Hygrometer", "D Anemometer", "B", "Barometer"],
    ["Who discovered penicillin?", "A Marie Curie", "B Alexander Fleming", "C Louis Pasteur", "D Gregor Mendel", "B", "Alexander Fleming"],
    ["Which organ in the human body produces insulin?", "A Liver", "B Pancreas", "C Kidney", "D Spleen", "B", "Pancreas"],
    ["Which country is the largest producer of coffee?", "A Brazil", "B India", "C Colombia", "D Ethiopia", "A", "Brazil"],
    ["Who wrote 'Wings of Fire'?", "A A.P.J. Abdul Kalam", "B R.K. Narayan", "C Chetan Bhagat", "D Arundhati Roy", "A", "A.P.J. Abdul Kalam"],
    ["Which is the fastest land animal?", "A Lion", "B Cheetah", "C Tiger", "D Gazelle", "B", "Cheetah"],
    ["Which gas is most abundant in Earth's atmosphere?", "A Oxygen", "B Nitrogen", "C Carbon Dioxide", "D Hydrogen", "B", "Nitrogen"],
    ["Which day is celebrated as World Environment Day?", "A 5th June", "B 22nd April", "C 1st May", "D 15th August", "A", "5th June"]
]

Level_2 = [
    ["Who was the founder of the Maurya Empire?", "A Chandragupta Maurya", "B Ashoka", "C Bindusara", "D Harsha", "A", "Chandragupta Maurya"],
    ["Which Indian classical dance form originated in Tamil Nadu?", "A Kathak", "B Bharatnatyam", "C Odissi", "D Kathakali", "B", "Bharatnatyam"],
    ["What is the powerhouse of the cell?", "A Nucleus", "B Ribosome", "C Mitochondria", "D Golgi apparatus", "C", "Mitochondria"],
    ["Which battle was fought in 1526 marking the beginning of Mughal rule in India?", "A Battle of Panipat", "B Battle of Plassey", "C Battle of Haldighati", "D Battle of Buxar", "A", "Battle of Panipat"],
    ["Who was the first President of independent India?", "A Rajendra Prasad", "B Jawaharlal Nehru", "C S. Radhakrishnan", "D Zakir Husain", "A", "Rajendra Prasad"],
    ["Which Indian state has the longest coastline?", "A Gujarat", "B Maharashtra", "C Tamil Nadu", "D Andhra Pradesh", "A", "Gujarat"],
    ["Who is known as the 'Father of the Indian Constitution'?", "A B.R. Ambedkar", "B Jawaharlal Nehru", "C Mahatma Gandhi", "D Sardar Patel", "A", "B.R. Ambedkar"],
    ["Which river is the longest in India?", "A Ganga", "B Yamuna", "C Godavari", "D Narmada", "A", "Ganga"],
    ["Which gas is commonly used in electric bulbs?", "A Nitrogen", "B Helium", "C Argon", "D Oxygen", "C", "Argon"],
    ["What is the main ingredient in making glass?", "A Sand", "B Clay", "C Limestone", "D Coal", "A", "Sand"],
    ["Which Indian state is famous for the 'Hornbill Festival'?", "A Nagaland", "B Assam", "C Manipur", "D Meghalaya", "A", "Nagaland"],
    ["Which vitamin is produced when the skin is exposed to sunlight?", "A Vitamin A", "B Vitamin B", "C Vitamin C", "D Vitamin D", "D", "Vitamin D"],
    ["Who is the author of the book 'India After Gandhi'?", "A Ramachandra Guha", "B Bipin Chandra", "C Romila Thapar", "D William Dalrymple", "A", "Ramachandra Guha"],
    ["What is the SI unit of electric current?", "A Volt", "B Ampere", "C Ohm", "D Watt", "B", "Ampere"],
    ["Which planet has the most moons?", "A Jupiter", "B Saturn", "C Uranus", "D Neptune", "B", "Saturn"],
    ["Who was the first woman judge of the Supreme Court of India?", "A Fathima Beevi", "B Leila Seth", "C Indu Malhotra", "D Ruma Pal", "A", "Fathima Beevi"],
    ["What is the full form of DNA?", "A Deoxyribonucleic Acid", "B Deoxyribonuclear Acid", "C Deoxynucleic Acid", "D Deoxynuclear Acid", "A", "Deoxyribonucleic Acid"],
    ["Which Indian city is known as the 'Electronic City of India'?", "A Bengaluru", "B Pune", "C Hyderabad", "D Chennai", "A", "Bengaluru"],
    ["Which is the highest civilian award in India?", "A Padma Shri", "B Bharat Ratna", "C Dronacharya Award", "D Arjuna Award", "B", "Bharat Ratna"],
    ["Which animal is the largest mammal on Earth?", "A African Elephant", "B Blue Whale", "C Giraffe", "D Hippopotamus", "B", "Blue Whale"]
]

Level_3 = [
    ["Which Mughal emperor built the Taj Mahal?", "A Akbar", "B Jahangir", "C Shah Jahan", "D Aurangzeb", "C", "Shah Jahan"],
    ["Which Indian state was formerly known as 'Orissa'?", "A Odisha", "B Kerala", "C Assam", "D Bihar", "A", "Odisha"],
    ["What is the capital of Arunachal Pradesh?", "A Itanagar", "B Imphal", "C Gangtok", "D Aizawl", "A", "Itanagar"],
    ["Who founded the Indian National Congress?", "A Mahatma Gandhi", "B Bal Gangadhar Tilak", "C Allan Octavian Hume", "D Jawaharlal Nehru", "C", "Allan Octavian Hume"],
    ["Which is the largest desert in India?", "A Thar Desert", "B Rann of Kutch", "C Cold Desert", "D Sunderbans", "A", "Thar Desert"],
    ["Which Indian state is known as the 'Spice Garden of India'?", "A Kerala", "B Tamil Nadu", "C Karnataka", "D Goa", "A", "Kerala"],
    ["Which language has the highest number of native speakers in India?", "A Hindi", "B Bengali", "C Telugu", "D Marathi", "A", "Hindi"],
    ["Who is called the 'Missile Man of India'?", "A Vikram Sarabhai", "B Homi Bhabha", "C A.P.J. Abdul Kalam", "D Satish Dhawan", "C", "A.P.J. Abdul Kalam"],
    ["Which year was the Goods and Services Tax (GST) introduced in India?", "A 2015", "B 2017", "C 2016", "D 2018", "B", "2017"],
    ["Which Indian state is famous for the Konark Sun Temple?", "A Odisha", "B West Bengal", "C Madhya Pradesh", "D Gujarat", "A", "Odisha"],
    ["What is the capital of Bhutan?", "A Thimphu", "B Kathmandu", "C Dhaka", "D Male", "A", "Thimphu"],
    ["Who was the first Indian to win a Nobel Prize?", "A Rabindranath Tagore", "B C.V. Raman", "C Amartya Sen", "D Mother Teresa", "A", "Rabindranath Tagore"],
    ["Which mountain range forms the northern boundary of India?", "A Himalayas", "B Aravalli", "C Vindhya", "D Satpura", "A", "Himalayas"],
    ["Which city is called the 'Silicon Valley of India'?", "A Hyderabad", "B Bengaluru", "C Pune", "D Chennai", "B", "Bengaluru"],
    ["Which Indian festival marks the victory of good over evil?", "A Holi", "B Diwali", "C Eid", "D Christmas", "B", "Diwali"],
    ["Which is the largest freshwater lake in India?", "A Dal Lake", "B Chilika Lake", "C Wular Lake", "D Loktak Lake", "C", "Wular Lake"],
    ["What does the term 'GDP' stand for?", "A Gross Domestic Product", "B General Domestic Product", "C Gross Development Plan", "D General Development Plan", "A", "Gross Domestic Product"],
    ["Who is the author of 'The Discovery of India'?", "A Jawaharlal Nehru", "B Mahatma Gandhi", "C B.R. Ambedkar", "D Rabindranath Tagore", "A", "Jawaharlal Nehru"],
    ["Which gas is used in refrigerators?", "A Chlorofluorocarbon", "B Carbon dioxide", "C Helium", "D Nitrogen", "A", "Chlorofluorocarbon"],
    ["Which city is the capital of Telangana?", "A Hyderabad", "B Vijayawada", "C Warangal", "D Amaravati", "A", "Hyderabad"]
]

Level_4 = [
    ["Who was the last Governor-General of independent India?", "A C. Rajagopalachari", "B Lord Mountbatten", "C Chakravarti Rajagopalachari", "D Viceroy of India", "A", "C. Rajagopalachari"],
    ["Which Article of the Indian Constitution deals with Fundamental Rights?", "A Article 12", "B Article 14-32", "C Article 370", "D Article 356", "B", "Article 14-32"],
    ["Which of the following is NOT a fundamental duty of Indian citizens?", "A To protect the environment", "B To safeguard public property", "C To pay taxes", "D To promote harmony", "C", "To pay taxes"],
    ["Which state is the largest producer of tea in India?", "A Assam", "B West Bengal", "C Tamil Nadu", "D Kerala", "A", "Assam"],
    ["Which Indian city hosted the 2010 Commonwealth Games?", "A Mumbai", "B Delhi", "C Chennai", "D Kolkata", "B", "Delhi"],
    ["Which Indian freedom fighter was known as 'Netaji'?", "A Mahatma Gandhi", "B Jawaharlal Nehru", "C Subhas Chandra Bose", "D Bhagat Singh", "C", "Subhas Chandra Bose"],
    ["Who composed the Indian national song 'Vande Mataram'?", "A Bankim Chandra Chatterjee", "B Rabindranath Tagore", "C Sarojini Naidu", "D Harivansh Rai Bachchan", "A", "Bankim Chandra Chatterjee"],
    ["Which is the largest national park in India?", "A Jim Corbett", "B Kaziranga", "C Hemis", "D Ranthambore", "C", "Hemis"],
    ["Which is the longest river in the world?", "A Amazon", "B Nile", "C Yangtze", "D Mississippi", "B", "Nile"],
    ["Which year was the Right to Information Act implemented in India?", "A 2002", "B 2005", "C 2010", "D 1999", "B", "2005"],
    ["Who was the first Indian woman to win an Olympic medal?", "A Mary Kom", "B P.V. Sindhu", "C Karnam Malleswari", "D Saina Nehwal", "C", "Karnam Malleswari"],
    ["What is the capital of the Andaman and Nicobar Islands?", "A Port Blair", "B Chennai", "C Visakhapatnam", "D Kolkata", "A", "Port Blair"],
    ["Which Indian state is known as the 'Land of the Rising Sun'?", "A Arunachal Pradesh", "B Manipur", "C Mizoram", "D Nagaland", "A", "Arunachal Pradesh"],
    ["Who was the founder of the Sikh religion?", "A Guru Nanak", "B Guru Gobind Singh", "C Guru Teg Bahadur", "D Guru Arjan", "A", "Guru Nanak"],
    ["Which Indian state has the highest literacy rate?", "A Kerala", "B Tamil Nadu", "C Maharashtra", "D Goa", "A", "Kerala"],
    ["Which is the largest gland in the human body?", "A Thyroid", "B Liver", "C Pancreas", "D Pituitary", "B", "Liver"],
    ["What is the currency of Bhutan?", "A Ngultrum", "B Rupee", "C Dollar", "D Taka", "A", "Ngultrum"],
    ["Who is the current Chief Justice of India? (as of 2025)", "A Dhananjaya Y. Chandrachud", "B Ranjan Gogoi", "C N.V. Ramana", "D Sharad Arvind Bobde", "A", "Dhananjaya Y. Chandrachud"],
    ["Which is the first state to implement 5G in India?", "A Maharashtra", "B Delhi", "C Karnataka", "D Tamil Nadu", "B", "Delhi"],
    ["Which Indian scientist invented the 'Zero' concept?", "A Aryabhata", "B Bhaskara I", "C Brahmagupta", "D Varahamihira", "A", "Aryabhata"]
]

Level_5 = [
    ["Which Indian state is known as the 'Land of Rising Sun'?", "A) Arunachal Pradesh", "B) Nagaland", "C) Sikkim", "D) Assam", "A", "Arunachal Pradesh"],
    ["Who was the first woman Prime Minister of India?", "A) Indira Gandhi", "B) Sarojini Naidu", "C) Pratibha Patil", "D) Sushma Swaraj", "A", "Indira Gandhi"],
    ["Which river is known as the 'Sorrow of Bihar'?", "A) Kosi", "B) Ganga", "C) Yamuna", "D) Mahanadi", "A", "Kosi"],
    ["Which Indian city is known as the 'Manchester of India'?", "A) Ahmedabad", "B) Surat", "C) Kanpur", "D) Mumbai", "A", "Ahmedabad"],
    ["Who wrote the book 'The Discovery of India'?", "A) Jawaharlal Nehru", "B) Mahatma Gandhi", "C) Subhas Chandra Bose", "D) B.R. Ambedkar", "A", "Jawaharlal Nehru"],
    ["Which is the smallest state in India by area?", "A) Goa", "B) Sikkim", "C) Mizoram", "D) Delhi", "A", "Goa"],
    ["Who was the first woman Chief Minister of an Indian state?", "A) Sucheta Kriplani", "B) Sarojini Naidu", "C) Rajkumari Amrit Kaur", "D) Vijayalakshmi Pandit", "A", "Sucheta Kriplani"],
    ["Which is the largest river island in India?", "A) Majuli", "B) Diu", "C) Srirangam", "D) Rameswaram", "A", "Majuli"],
    ["Who was the first Indian to win a Nobel Prize?", "A) Rabindranath Tagore", "B) C.V. Raman", "C) Har Gobind Khorana", "D) Subrahmanyan Chandrasekhar", "A", "Rabindranath Tagore"],
    ["Which Indian state is known as the 'Spice Garden of India'?", "A) Kerala", "B) Tamil Nadu", "C) Andhra Pradesh", "D) Karnataka", "A", "Kerala"],
    ["Who was the first Indian to win an individual Olympic gold medal?", "A) Abhinav Bindra", "B) Leander Paes", "C) Rajyavardhan Singh Rathore", "D) Karnam Malleswari", "A", "Abhinav Bindra"],
    ["Which is the largest city in India by population?", "A) Mumbai", "B) Delhi", "C) Kolkata", "D) Bengaluru", "A", "Mumbai"],
    ["Who was the first woman President of India?", "A) Pratibha Patil", "B) Sarojini Naidu", "C) Indira Gandhi", "D) Sushma Swaraj", "A", "Pratibha Patil"],
    ["Which is the longest river in India?", "A) Ganga", "B) Yamuna", "C) Godavari", "D) Brahmaputra", "A", "Ganga"],
    ["Who was the first Indian to become the Chief Justice of India?", "A) Harilal Jekisundas Kania", "B) M. Patanjali Sastri", "C) B.K. Mukherjea", "D) P.B. Gajendragadkar", "A", "Harilal Jekisundas Kania"],
    ["Which is the highest civilian award in India?", "A) Bharat Ratna", "B) Padma Vibhushan", "C) Padma Bhushan", "D) Padma Shri", "A", "Bharat Ratna"],
    ["Who was the first woman to climb Mount Everest?", "A) Junko Tabei", "B) Bachendri Pal", "C) Santosh Yadav", "D) Arjun Singh", "A", "Junko Tabei"],
    ["Which is the first state in India to implement the Right to Information Act?", "A) Tamil Nadu", "B) Kerala", "C) Goa", "D) Rajasthan", "D", "Rajasthan"],
    ["Who was the first Indian to win a Grammy Award?", "A) Ravi Shankar", "B) Zakir Hussain", "C) Tanvi Shah", "D) A.R. Rahman", "C", "Tanvi Shah"],
    ["Which is the first Indian state to be formed on a linguistic basis?", "A) Andhra Pradesh", "B) Kerala", "C) Maharashtra", "D) Punjab", "A", "Andhra Pradesh"]
]

Level_6 = [
    ["Which Indian state is known as the 'Land of Rising Sun'?", "A Arunachal Pradesh", "B Nagaland", "C Sikkim", "D Assam", "A", "Arunachal Pradesh"],
    ["Who was the first woman Prime Minister of India?", "A Indira Gandhi", "B Sarojini Naidu", "C Pratibha Patil", "D Sushma Swaraj", "A", "Indira Gandhi"],
    ["Which river is known as the 'Sorrow of Bihar'?", "A Kosi", "B Ganga", "C Yamuna", "D Mahanadi", "A", "Kosi"],
    ["Which Indian city is known as the 'Manchester of India'?", "A Ahmedabad", "B Surat", "C Kanpur", "D Mumbai", "A", "Ahmedabad"],
    ["Who wrote the book 'The Discovery of India'?", "A Jawaharlal Nehru", "B Mahatma Gandhi", "C Subhas Chandra Bose", "D B.R. Ambedkar", "A", "Jawaharlal Nehru"],
    ["Which is the smallest state in India by area?", "A Goa", "B Sikkim", "C Mizoram", "D Delhi", "A", "Goa"],
    ["Who was the first woman Chief Minister of an Indian state?", "A Sucheta Kriplani", "B Sarojini Naidu", "C Rajkumari Amrit Kaur", "D Vijayalakshmi Pandit", "A", "Sucheta Kriplani"],
    ["Which is the largest river island in India?", "A Majuli", "B Diu", "C Srirangam", "D Rameswaram", "A", "Majuli"],
    ["Who was the first Indian to win a Nobel Prize?", "A Rabindranath Tagore", "B C.V. Raman", "C Har Gobind Khorana", "D Subrahmanyan Chandrasekhar", "A", "Rabindranath Tagore"],
    ["Which Indian state is known as the 'Spice Garden of India'?", "A Kerala", "B Tamil Nadu", "C Andhra Pradesh", "D Karnataka", "A", "Kerala"],
    ["Who was the first Indian to win an individual Olympic gold medal?", "A Abhinav Bindra", "B Leander Paes", "C Rajyavardhan Singh Rathore", "D Karnam Malleswari", "A", "Abhinav Bindra"],
    ["Which is the largest city in India by population?", "A Mumbai", "B Delhi", "C Kolkata", "D Bengaluru", "A", "Mumbai"],
    ["Who was the first woman President of India?", "A Pratibha Patil", "B Sarojini Naidu", "C Indira Gandhi", "D Sushma Swaraj", "A", "Pratibha Patil"],
    ["Which is the longest river in India?", "A Ganga", "B Yamuna", "C Godavari", "D Brahmaputra", "A", "Ganga"],
    ["Who was the first Indian to become the Chief Justice of India?", "A Harilal Jekisundas Kania", "B M. Patanjali Sastri", "C B.K. Mukherjea", "D P.B. Gajendragadkar", "A", "Harilal Jekisundas Kania"],
    ["Which is the highest civilian award in India?", "A Bharat Ratna", "B Padma Vibhushan", "C Padma Bhushan", "D Padma Shri", "A", "Bharat Ratna"],
    ["Who was the first woman to climb Mount Everest?", "A Junko Tabei", "B Bachendri Pal", "C Santosh Yadav", "D Arjun Singh", "A", "Junko Tabei"],
    ["Which is the first state in India to implement the Right to Information Act?", "A Tamil Nadu", "B Kerala", "C Goa", "D Rajasthan", "D", "Rajasthan"],
    ["Who was the first Indian to win a Grammy Award?", "A Ravi Shankar", "B Zakir Hussain", "C Tanvi Shah", "D A.R. Rahman", "C", "Tanvi Shah"],
    ["Which is the first Indian state to be formed on a linguistic basis?", "A Andhra Pradesh", "B Kerala", "C Maharashtra", "D Punjab", "A", "Andhra Pradesh"]
]

Level_7 = [
    ["Which Indian state is the leading producer of saffron?", "A Jammu & Kashmir", "B Himachal Pradesh", "C Uttar Pradesh", "D Rajasthan", "A", "Jammu & Kashmir"],
    ["Who was the first Indian to win the Booker Prize?", "A Arundhati Roy", "B Kiran Desai", "C Vikram Seth", "D Salman Rushdie", "A", "Arundhati Roy"],
    ["Which is the only Indian state to have a coastline on the Bay of Bengal, Arabian Sea, and the Indian Ocean?", "A Tamil Nadu", "B Andhra Pradesh", "C Kerala", "D Odisha", "A", "Tamil Nadu"],
    ["Who was the first woman to become the Chief Justice of a High Court in India?", "A Leila Seth", "B Fathima Beevi", "C Ruma Pal", "D Sujata V. Manohar", "A", "Leila Seth"],
    ["Which city is known as the 'City of Joy'?", "A Kolkata", "B Chennai", "C Bengaluru", "D Hyderabad", "A", "Kolkata"],
    ["Which is the first Indian state to implement the Goods and Services Tax (GST)?", "A Assam", "B Bihar", "C Gujarat", "D Maharashtra", "A", "Assam"],
    ["Who was the first Indian to win an Olympic medal?", "A Khashaba Dadasaheb Jadhav", "B Norman Pritchard", "C KD Jadhav", "D Michael Phelps", "A", "Khashaba Dadasaheb Jadhav"],
    ["Which is the first Indian state to achieve 100% literacy?", "A Kerala", "B Goa", "C Sikkim", "D Mizoram", "A", "Kerala"],
    ["Who was the first Indian to win the Nobel Prize in Physics?", "A C.V. Raman", "B Subrahmanyan Chandrasekhar", "C Har Gobind Khorana", "D Venkatraman Ramakrishnan", "A", "C.V. Raman"],
    ["Which is the first Indian state to have a separate agriculture budget?", "A Telangana", "B Andhra Pradesh", "C Punjab", "D Haryana", "A", "Telangana"],
    ["Who was the first Indian to win the Booker Prize twice?", "A Arundhati Roy", "B Kiran Desai", "C Salman Rushdie", "D Vikram Seth", "A", "Arundhati Roy"],
    ["Which is the first Indian state to implement the National Food Security Act?", "A Chhattisgarh", "B Madhya Pradesh", "C Odisha", "D Uttar Pradesh", "A", "Chhattisgarh"],
    ["Who was the first Indian to win the Nobel Prize in Chemistry?", "A C.N.R. Rao", "B Venkatraman Ramakrishnan", "C Har Gobind Khorana", "D Subrahmanyan Chandrasekhar", "B", "Venkatraman Ramakrishnan"],
    ["Which is the first Indian state to have a separate budget for women and children?", "A Kerala", "B Tamil Nadu", "C Rajasthan", "D Madhya Pradesh", "A", "Kerala"],
    ["Who was the first Indian to win the Nobel Prize in Peace?", "A Mother Teresa", "B Jawaharlal Nehru", "C Mahatma Gandhi", "D Subhas Chandra Bose", "A", "Mother Teresa"],
    ["Which is the first Indian state to have a separate budget for education?", "A Kerala", "B Gujarat", "C Maharashtra", "D Tamil Nadu", "A", "Kerala"],
    ["Who was the first Indian to win the Nobel Prize in Literature?", "A Rabindranath Tagore", "B R.K. Narayan", "C Mulk Raj Anand", "D Kamala Das", "A", "Rabindranath Tagore"],
    ["Which is the first Indian state to have a separate budget for health?", "A Kerala", "B Tamil Nadu", "C Maharashtra", "D Andhra Pradesh", "A", "Kerala"],
    ["Who was the first Indian to win the Nobel Prize in Economics?", "A Amartya Sen", "B Manmohan Singh", "C Raghuram Rajan", "D Jagdish Bhagwati", "A", "Amartya Sen"],
    ["Which is the first Indian state to have a separate budget for rural development?", "A Kerala", "B Tamil Nadu", "C Andhra Pradesh", "D Rajasthan", "A", "Kerala"]
]