Level_1 = [
    ["Who wrote India's national anthem?", "A) Lal Bahadur Shastri", "B) Rabindranath Tagore", "C) Chetan Bhagat", "D) R.K. Narayan", "Rabindranath Tagore"],
    ["Which god is also called 'Gauri Nandan'?", "A) Agni", "B) Indra", "C) Hanuman", "D) Ganesha", "Ganesha"],
    ["Which city is known as the 'Pink City' of India?", "A) Bengaluru", "B) Mysore", "C) Jaipur", "D) Kochi", "Jaipur"],
    ["Which festival is known as the festival of lights?", "A) Holi", "B) Eid", "C) Diwali", "D) Baisakhi", "Diwali"],
    ["How many players are there in a cricket team?", "A) 9", "B) 10", "C) 11", "D) 12", "11"],
    ["What is the capital of India?", "A) Mumbai", "B) Delhi", "C) Kolkata", "D) Chennai", "Delhi"],
    ["What is the currency of India?", "A) Dollar", "B) Euro", "C) Rupee", "D) Pound", "Rupee"],
    ["What do we call a house made of ice?", "A) Tent", "B) Igloo", "C) Hut", "D) Cottage", "Igloo"],
    ["Which bird is known for mimicking human speech?", "A) Crow", "B) Pigeon", "C) Parrot", "D) Eagle", "Parrot"],
    ["Which is the largest continent?", "A) Europe", "B) Africa", "C) Asia", "D) Australia", "Asia"],
    ["Which is considered the world's first university?", "A) University of Paris", "B) University of Allahabad", "C) Takshashila University", "D) Assam University", "Takshashila University"],
    ["Which is the national animal of India?", "A) Lion", "B) Elephant", "C) Tiger", "D) Cow", "Tiger"],
    ["Which shape has 4 equal sides?", "A) Rectangle", "B) Triangle", "C) Square", "D) Circle", "Square"],
    ["What does the heart pump?", "A) Water", "B) Oxygen", "C) Blood", "D) Air", "Blood"],
    ["Which planet is known as the Red Planet?", "A) Earth", "B) Mars", "C) Jupiter", "D) Venus", "Mars"],
    ["Which vegetable is known as 'King of Vegetables'?", "A) Potato", "B) Tomato", "C) Brinjal", "D) Carrot", "Brinjal"],
    ["Which colour is made by mixing red and yellow?", "A) Blue", "B) Orange", "C) Green", "D) Purple", "Orange"],
    ["How many days are there in a week?", "A) 5", "B) 6", "C) 7", "D) 8", "7"],
    ["Which animal is known as the 'Ship of the Desert'?", "A) Horse", "B) Donkey", "C) Camel", "D) Elephant", "Camel"],
    ["Which is the smallest month in terms of days?", "A) January", "B) February", "C) March", "D) April", "February"],
    ["What is H2O?", "A) Salt", "B) Hydrogen", "C) Water", "D) Oxygen", "Water"],
    ["How many wheels does an auto rickshaw have?", "A) 2", "B) 3", "C) 4", "D) 6", "3"],
    ["What colour is the sun?", "A) Red", "B) Blue", "C) Yellow", "D) White", "Yellow"],
    ["How many alphabets are there in English?", "A) 24", "B) 25", "C) 26", "D) 27", "26"],
    ["What do bees make?", "A) Milk", "B) Wax", "C) Oil", "D) Honey", "Honey"]
]

Level_2 = [
    ["Where is the India Gate located?", "A) Agra", "B) Punjab", "C) Mumbai", "D) New Delhi", "New Delhi"],
    ["How many major religions are practiced in India?", "A) 6", "B) 7", "C) 8", "D) 4", "6"],
    ["On which date is Hindi Diwas celebrated?", "A) 13 September", "B) 14 September", "C) 14 July", "D) 15 August", "14 September"],
    ["Which is the longest river in India?", "A) Yamuna", "B) Ganga", "C) Brahmaputra", "D) Godavari", "Ganga"],
    ["What is the capital of West Bengal?", "A) Delhi", "B) Mumbai", "C) Kolkata", "D) Hyderabad", "Kolkata"],
    ["Who is known as the 'Father of the Nation'?", "A) Jawaharlal Nehru", "B) Mahatma Gandhi", "C) Sardar Patel", "D) B.R. Ambedkar", "Mahatma Gandhi"],
    ["Which city is called the 'Silicon Valley of India'?", "A) Hyderabad", "B) Pune", "C) Bengaluru", "D) Chennai", "Bengaluru"],
    ["Who was the first woman Prime Minister of India?", "A) Pratibha Patil", "B) Sonia Gandhi", "C) Indira Gandhi", "D) Sarojini Naidu", "Indira Gandhi"],
    ["What is the capital of Maharashtra?", "A) Mumbai", "B) Nagpur", "C) Pune", "D) Nashik", "Mumbai"],
    ["Which state is famous for Bihu festival?", "A) Punjab", "B) Assam", "C) Odisha", "D) West Bengal", "Assam"],
    ["What is the main language spoken in Tamil Nadu?", "A) Kannada", "B) Telugu", "C) Malayalam", "D) Tamil", "Tamil"],
    ["Who is the author of the book 'Wings of Fire'?", "A) A.P.J. Abdul Kalam", "B) Ratan Tata", "C) Chetan Bhagat", "D) Arundhati Roy", "A.P.J. Abdul Kalam"],
    ["Which is the national flower of India?", "A) Rose", "B) Marigold", "C) Lotus", "D) Sunflower", "Lotus"],
    ["Who invented the light bulb?", "A) Isaac Newton", "B) Albert Einstein", "C) Thomas Edison", "D) Nikola Tesla", "Thomas Edison"],
    ["Which gas do plants absorb?", "A) Oxygen", "B) Carbon Dioxide", "C) Nitrogen", "D) Hydrogen", "Carbon Dioxide"],
    ["In which year did India gain independence?", "A) 1945", "B) 1946", "C) 1947", "D) 1950", "1947"],
    ["Who composed the music for the Indian National Anthem?", "A) Ravi Shankar", "B) A.R. Rahman", "C) Rabindranath Tagore", "D) Bismillah Khan", "Rabindranath Tagore"],
    ["What is the chemical formula for salt?", "A) H2O", "B) CO2", "C) NaCl", "D) O2", "NaCl"],
    ["Which organ purifies blood in the human body?", "A) Heart", "B) Liver", "C) Kidney", "D) Lungs", "Kidney"],
    ["Which freedom fighter said 'Give me blood, and I shall give you freedom'?", "A) Bhagat Singh", "B) Subhas Chandra Bose", "C) Mahatma Gandhi", "D) Lala Lajpat Rai", "Subhas Chandra Bose"],
    ["What is the scientific name of human beings?", "A) Homo erectus", "B) Homo sapiens", "C) Homo neanderthalensis", "D) Primates", "Homo sapiens"],
    ["What does CPU stand for?", "A) Central Process Unit", "B) Central Processing Unit", "C) Central Processor Utility", "D) Computer Processing Unit", "Central Processing Unit"],
    ["What is the capital of Kerala?", "A) Kochi", "B) Kozhikode", "C) Thiruvananthapuram", "D) Kollam", "Thiruvananthapuram"],
    ["Which Mughal emperor built the Red Fort?", "A) Akbar", "B) Babur", "C) Shah Jahan", "D) Humayun", "Shah Jahan"],
    ["Which part of the plant conducts photosynthesis?", "A) Root", "B) Stem", "C) Flower", "D) Leaf", "Leaf"]
]

Level_3 = [
    ["Who wrote the book 'Dastan-e-Ghadar'?", "A) Mir Taqi Mir", "B) Mohammad Ibrahim Zauq", "C) Zahir Dehlvi", "D) Abul Qasim Firdausi", "Zahir Dehlvi"],
    ["Who is credited with the dialogue between King Milinda and the monk in 'Milinda Panha'?", "A) Nagasena", "B) Vasubandhu", "C) Nagarjuna", "D) Ashvaghosha", "Nagasena"],
    ["Who wrote the patriotic song 'Vande Mataram'?", "A) Rabindranath Tagore", "B) Bankim Chandra Chattopadhyay", "C) Ishwar Chandra Vidyasagar", "D) Subhas Chandra Bose", "Bankim Chandra Chattopadhyay"],
    ["Which river is also known as Dakshina Ganga?", "A) Narmada", "B) Krishna", "C) Godavari", "D) Kaveri", "Godavari"],
    ["Who built the Konark Sun Temple?", "A) Narasimhadeva I", "B) Ashoka", "C) Akbar", "D) Rajaraja Chola", "Narasimhadeva I"],
    ["Who was the first Indian to win an individual Olympic gold medal?", "A) Leander Paes", "B) Abhinav Bindra", "C) Milkha Singh", "D) Sushil Kumar", "Abhinav Bindra"],
    ["What is the study of fossils called?", "A) Zoology", "B) Botany", "C) Paleontology", "D) Ecology", "Paleontology"],
    ["Which is the oldest known civilization in the Indian subcontinent?", "A) Vedic", "B) Indus Valley", "C) Maurya", "D) Gupta", "Indus Valley"],
    ["Who is the author of 'Discovery of India'?", "A) Subhas Chandra Bose", "B) Mahatma Gandhi", "C) Jawaharlal Nehru", "D) B.R. Ambedkar", "Jawaharlal Nehru"],
    ["Which country was first to grant women the right to vote?", "A) USA", "B) UK", "C) New Zealand", "D) Australia", "New Zealand"],
    ["Which acid is found in the stomach?", "A) Sulphuric acid", "B) Hydrochloric acid", "C) Nitric acid", "D) Acetic acid", "Hydrochloric acid"],
    ["Which element has the highest melting point?", "A) Iron", "B) Tungsten", "C) Lead", "D) Platinum", "Tungsten"],
    ["Which Mughal ruler was defeated by Sher Shah Suri?", "A) Humayun", "B) Akbar", "C) Jahangir", "D) Aurangzeb", "Humayun"],
    ["Which Indian state has the longest coastline?", "A) Kerala", "B) Tamil Nadu", "C) Gujarat", "D) Maharashtra", "Gujarat"],
    ["Who is the founder of Sikhism?", "A) Guru Tegh Bahadur", "B) Guru Gobind Singh", "C) Guru Nanak", "D) Guru Angad", "Guru Nanak"],
    ["Where is the headquarters of the ISRO located?", "A) Hyderabad", "B) Bengaluru", "C) Chennai", "D) Delhi", "Bengaluru"],
    ["What is the SI unit of electric current?", "A) Volt", "B) Ampere", "C) Ohm", "D) Watt", "Ampere"],
    ["Who composed the epic poem 'Meghaduta'?", "A) Valmiki", "B) Kalidasa", "C) Tulsidas", "D) Bharavi", "Kalidasa"],
    ["Which Indian classical dance form originated in Kerala?", "A) Bharatnatyam", "B) Kathak", "C) Mohiniyattam", "D) Odissi", "Mohiniyattam"],
    ["What is the name of the first artificial satellite launched by India?", "A) Aryabhata", "B) Bhaskara", "C) INSAT-1A", "D) Rohini", "Aryabhata"],
    ["Who discovered the vaccine for smallpox?", "A) Edward Jenner", "B) Louis Pasteur", "C) Alexander Fleming", "D) Robert Koch", "Edward Jenner"],
    ["In which year did the Jallianwala Bagh massacre take place?", "A) 1917", "B) 1919", "C) 1920", "D) 1922", "1919"],
    ["Which Indian won the Nobel Peace Prize in 2014?", "A) Kailash Satyarthi", "B) Malala Yousafzai", "C) Amartya Sen", "D) Mother Teresa", "Kailash Satyarthi"],
    ["Which rock-cut cave temples are located in Maharashtra?", "A) Ajanta", "B) Mahabalipuram", "C) Ellora", "D) Both A and C", "Both A and C"],
    ["Which festival is known as the 'Festival of Sacrifice'?", "A) Diwali", "B) Holi", "C) Eid al-Adha", "D) Eid al-Fitr", "Eid al-Adha"]
]

Level_4 = [
    ["Who composed the Indian epic 'Mahabharata'?", "A) Vyasa", "B) Valmiki", "C) Kalidasa", "D) Bhasa", "Vyasa"],
    ["Which ancient university was located in Bihar?", "A) Taxila", "B) Nalanda", "C) Vikramshila", "D) Ujjain", "Nalanda"],
    ["Who discovered the law of planetary motion?", "A) Newton", "B) Kepler", "C) Galileo", "D) Copernicus", "Kepler"],
    ["Which Indian king defeated Seleucus I?", "A) Ashoka", "B) Chandragupta Maurya", "C) Samudragupta", "D) Harsha", "Chandragupta Maurya"],
    ["Which Indian physicist was awarded the Nobel Prize for the Raman Effect?", "A) S.N. Bose", "B) Homi Bhabha", "C) C.V. Raman", "D) Meghnad Saha", "C.V. Raman"],
    ["Which Veda contains hymns dedicated to gods?", "A) Samaveda", "B) Rigveda", "C) Yajurveda", "D) Atharvaveda", "Rigveda"],
    ["Where is the famous 'Brihadeeswara Temple' located?", "A) Kanchipuram", "B) Madurai", "C) Thanjavur", "D) Chennai", "Thanjavur"],
    ["Who was the first Indian woman to climb Mount Everest?", "A) Bachendri Pal", "B) Arunima Sinha", "C) Santosh Yadav", "D) Premlata Agarwal", "Bachendri Pal"],
    ["Which act was passed after the Sepoy Mutiny of 1857?", "A) Government of India Act 1858", "B) Rowlatt Act", "C) Indian Councils Act", "D) Indian Independence Act", "Government of India Act 1858"],
    ["Which river flows through the Grand Canyon?", "A) Colorado", "B) Mississippi", "C) Missouri", "D) Amazon", "Colorado"],
    ["Which Indian ruler is known as 'Napoleon of India'?", "A) Chandragupta I", "B) Samudragupta", "C) Harshavardhana", "D) Ashoka", "Samudragupta"],
    ["What is the unit of measurement for the intensity of sound?", "A) Hertz", "B) Decibel", "C) Watt", "D) Ampere", "Decibel"],
    ["Who among the following was known as the Iron Man of India?", "A) Jawaharlal Nehru", "B) Subhas Chandra Bose", "C) Sardar Vallabhbhai Patel", "D) Lal Bahadur Shastri", "Sardar Vallabhbhai Patel"],
    ["Who introduced the Doctrine of Lapse?", "A) Lord Wellesley", "B) Lord Dalhousie", "C) Lord Canning", "D) Lord Curzon", "Lord Dalhousie"],
    ["Who was the last Governor-General of independent India?", "A) Rajendra Prasad", "B) Lord Mountbatten", "C) C. Rajagopalachari", "D) Jawaharlal Nehru", "C. Rajagopalachari"],
    ["In which language was the Buddhist scripture Tripitaka written?", "A) Sanskrit", "B) Prakrit", "C) Pali", "D) Tamil", "Pali"],
    ["Which Indian mathematician is known for his work in number theory?", "A) Aryabhata", "B) Bhaskaracharya", "C) Ramanujan", "D) Varahamihira", "Ramanujan"],
    ["Which is the largest gland in the human body?", "A) Pancreas", "B) Liver", "C) Thyroid", "D) Adrenal", "Liver"],
    ["Who is known as the Missile Man of India?", "A) Vikram Sarabhai", "B) Homi Bhabha", "C) Abdul Kalam", "D) Satish Dhawan", "Abdul Kalam"],
    ["In which year did the Battle of Plassey take place?", "A) 1757", "B) 1764", "C) 1776", "D) 1782", "1757"],
    ["Which Indian freedom fighter formed the Azad Hind Fauj?", "A) Bhagat Singh", "B) Chandrashekhar Azad", "C) Subhas Chandra Bose", "D) Lala Lajpat Rai", "Subhas Chandra Bose"],
    ["Which hormone regulates blood sugar?", "A) Adrenaline", "B) Insulin", "C) Thyroxine", "D) Estrogen", "Insulin"],
    ["Where is the Valley of Flowers located?", "A) Himachal Pradesh", "B) Uttarakhand", "C) Jammu & Kashmir", "D) Arunachal Pradesh", "Uttarakhand"],
    ["Which planet has the most moons?", "A) Jupiter", "B) Saturn", "C) Uranus", "D) Neptune", "Saturn"],
    ["Which is the deepest ocean in the world?", "A) Atlantic", "B) Indian", "C) Arctic", "D) Pacific", "Pacific"]
]

Level_5 = [
    ["What is the smallest bone in the human body?", "A) Femur", "B) Stapes", "C) Ulna", "D) Tibia", "Stapes"],
    ["Which Indian scientist won the Nobel Prize for Physics in 1930?", "A) C.V. Raman", "B) Homi Bhabha", "C) S. Chandrasekhar", "D) Jagadish Chandra Bose", "C.V. Raman"],
    ["Which gas is most abundant in the Earth's atmosphere?", "A) Oxygen", "B) Carbon Dioxide", "C) Nitrogen", "D) Hydrogen", "Nitrogen"],
    ["In which year did the Titanic sink?", "A) 1910", "B) 1912", "C) 1920", "D) 1905", "1912"],
    ["Which Mughal emperor built the Red Fort?", "A) Akbar", "B) Humayun", "C) Shah Jahan", "D) Aurangzeb", "Shah Jahan"],
    ["What is the SI unit of electric current?", "A) Volt", "B) Ampere", "C) Ohm", "D) Watt", "Ampere"],
    ["Who is the author of 'Wings of Fire'?", "A) Vikram Seth", "B) Abdul Kalam", "C) Arundhati Roy", "D) R.K. Narayan", "Abdul Kalam"],
    ["Which is the largest desert in the world?", "A) Gobi", "B) Thar", "C) Sahara", "D) Antarctic", "Antarctic"],
    ["In Hindu mythology, who is the consort of Lord Vishnu?", "A) Durga", "B) Lakshmi", "C) Saraswati", "D) Parvati", "Lakshmi"],
    ["What is the boiling point of water at sea level?", "A) 100°F", "B) 212°C", "C) 100°C", "D) 0°C", "100°C"],
    ["What is the name of India's first satellite?", "A) INSAT", "B) Aryabhata", "C) Bhaskara", "D) Rohini", "Aryabhata"],
    ["Which planet has the most moons?", "A) Earth", "B) Mars", "C) Jupiter", "D) Saturn", "Saturn"],
    ["What is the capital of Canada?", "A) Toronto", "B) Vancouver", "C) Ottawa", "D) Montreal", "Ottawa"],
    ["In which year did India become a republic?", "A) 1947", "B) 1950", "C) 1952", "D) 1962", "1950"],
    ["Who invented the World Wide Web?", "A) Bill Gates", "B) Tim Berners-Lee", "C) Steve Jobs", "D) Elon Musk", "Tim Berners-Lee"],
    ["Which river is called the 'Sorrow of Bengal'?", "A) Ganga", "B) Yamuna", "C) Damodar", "D) Kaveri", "Damodar"],
    ["Which is the longest written constitution in the world?", "A) USA", "B) UK", "C) India", "D) Australia", "India"],
    ["What is the currency of South Korea?", "A) Yen", "B) Won", "C) Baht", "D) Dollar", "Won"],
    ["Which of these is a scalar quantity?", "A) Velocity", "B) Acceleration", "C) Force", "D) Speed", "Speed"],
    ["Who was the first Indian woman to go to space?", "A) Kalpana Chawla", "B) Sunita Williams", "C) Ritu Karidhal", "D) Tessy Thomas", "Kalpana Chawla"],
    ["Who is the founder of the Sikh religion?", "A) Guru Nanak", "B) Guru Gobind Singh", "C) Guru Tegh Bahadur", "D) Guru Angad", "Guru Nanak"],
    ["Which instrument is used to measure earthquakes?", "A) Thermometer", "B) Barometer", "C) Seismograph", "D) Altimeter", "Seismograph"],
    ["Which vitamin is produced by sunlight in the human body?", "A) Vitamin A", "B) Vitamin B", "C) Vitamin C", "D) Vitamin D", "Vitamin D"],
    ["What does DNA stand for?", "A) Deoxyribonucleic Acid", "B) Dynamic Neural Application", "C) Digital Network Access", "D) Deoxidized Nucleic Atom", "Deoxyribonucleic Acid"],
    ["Which is the highest civilian award in India?", "A) Padma Shri", "B) Padma Bhushan", "C) Bharat Ratna", "D) Padma Vibhushan", "Bharat Ratna"]
]

Level_6 = [
    ["Who invented the telephone?", "A) Alexander Graham Bell", "B) Thomas Edison", "C) Nikola Tesla", "D) Guglielmo Marconi", "Alexander Graham Bell"],
    ["Which planet is known for its prominent rings?", "A) Jupiter", "B) Saturn", "C) Uranus", "D) Neptune", "Saturn"],
    ["What is often called the powerhouse of the cell?", "A) Nucleus", "B) Ribosome", "C) Mitochondria", "D) Chloroplast", "Mitochondria"],
    ["In which year did World War II end?", "A) 1942", "B) 1945", "C) 1950", "D) 1939", "1945"],
    ["Which element has the chemical symbol 'Fe'?", "A) Fluorine", "B) Iron", "C) Francium", "D) Flerovium", "Iron"],
    ["Who painted the Mona Lisa?", "A) Michelangelo", "B) Vincent van Gogh", "C) Pablo Picasso", "D) Leonardo da Vinci", "Leonardo da Vinci"],
    ["What is the largest mammal on Earth?", "A) African Elephant", "B) Blue Whale", "C) Giraffe", "D) Great White Shark", "Blue Whale"],
    ["Which country hosted the 2016 Summer Olympics?", "A) China", "B) UK", "C) Brazil", "D) Russia", "Brazil"],
    ["What is the square root of 144?", "A) 10", "B) 11", "C) 12", "D) 13", "12"],
    ["What is the capital city of Japan?", "A) Osaka", "B) Kyoto", "C) Tokyo", "D) Nagoya", "Tokyo"],
    ["Who wrote 'Romeo and Juliet'?", "A) William Shakespeare", "B) John Milton", "C) Charles Dickens", "D) Mark Twain", "William Shakespeare"],
    ["What is the boiling point of water (in °C)?", "A) 90°C", "B) 80°C", "C) 100°C", "D) 110°C", "100°C"],
    ["Which instrument measures atmospheric pressure?", "A) Thermometer", "B) Barometer", "C) Hygrometer", "D) Anemometer", "Barometer"],
    ["Which gas do plants absorb for photosynthesis?", "A) Oxygen", "B) Nitrogen", "C) Carbon Dioxide", "D) Hydrogen", "Carbon Dioxide"],
    ["Who discovered penicillin?", "A) Louis Pasteur", "B) Alexander Fleming", "C) Marie Curie", "D) Joseph Lister", "Alexander Fleming"],
    ["What is the largest planet in our Solar System?", "A) Saturn", "B) Jupiter", "C) Neptune", "D) Earth", "Jupiter"],
    ["Which language is primarily spoken in Brazil?", "A) Spanish", "B) Portuguese", "C) French", "D) English", "Portuguese"],
    ["What is the smallest prime number?", "A) 1", "B) 2", "C) 3", "D) 5", "2"],
    ["Which organ is responsible for pumping blood?", "A) Brain", "B) Lung", "C) Heart", "D) Kidney", "Heart"],
    ["Who is known as the 'Father of Geometry'?", "A) Pythagoras", "B) Euclid", "C) Archimedes", "D) Aristotle", "Euclid"],
    ["Which ocean is the largest?", "A) Atlantic", "B) Indian", "C) Arctic", "D) Pacific", "Pacific"],
    ["Who developed the theory of relativity?", "A) Isaac Newton", "B) Nikola Tesla", "C) Albert Einstein", "D) Galileo Galilei", "Albert Einstein"],
    ["What is H2SO4 commonly known as?", "A) Hydrochloric Acid", "B) Sulfuric Acid", "C) Nitric Acid", "D) Acetic Acid", "Sulfuric Acid"],
    ["Which country is known as the Land of the Rising Sun?", "A) China", "B) South Korea", "C) Japan", "D) Thailand", "Japan"],
    ["What is the main ingredient in guacamole?", "A) Tomato", "B) Avocado", "C) Cucumber", "D) Onion", "Avocado"]
]

Level_7 = [
    ["Which novel begins with 'Call me Ishmael'?", "A) Moby Dick", "B) The Old Man and the Sea", "C) Twenty Thousand Leagues Under the Seas", "D) Robinson Crusoe", "Moby Dick"],
    ["What is the hardest natural substance on Earth?", "A) Corundum", "B) Diamond", "C) Graphite", "D) Quartz", "Diamond"],
    ["Who formulated the laws of motion?", "A) Galileo Galilei", "B) Isaac Newton", "C) Johannes Kepler", "D) Albert Einstein", "Isaac Newton"],
    ["Which country gifted the Statue of Liberty to the USA?", "A) England", "B) France", "C) Germany", "D) Spain", "France"],
    ["Who composed 'The Four Seasons'?", "A) Johann Sebastian Bach", "B) Wolfgang Amadeus Mozart", "C) Antonio Vivaldi", "D) Ludwig van Beethoven", "Antonio Vivaldi"],
    ["Which is the longest river in the world?", "A) Amazon", "B) Nile", "C) Yangtze", "D) Mississippi", "Nile"],
    ["Who wrote 'The Divine Comedy'?", "A) Dante Alighieri", "B) Geoffrey Chaucer", "C) John Milton", "D) Victor Hugo", "Dante Alighieri"],
    ["What is the chemical formula for ozone?", "A) O2", "B) O3", "C) CO2", "D) H2O", "O3"],
    ["Which element has the atomic number 79?", "A) Platinum", "B) Gold", "C) Mercury", "D) Silver", "Gold"],
    ["What is the capital of Iceland?", "A) Reykjavik", "B) Oslo", "C) Helsinki", "D) Copenhagen", "Reykjavik"],
    ["Who discovered the structure of DNA?", "A) Watson and Crick", "B) Rosalind Franklin", "C) Linus Pauling", "D) Francis Crick", "Watson and Crick"],
    ["Which battle marked the end of Napoleon's rule?", "A) Battle of Trafalgar", "B) Battle of Austerlitz", "C) Battle of Waterloo", "D) Battle of Leipzig", "Battle of Waterloo"],
    ["Who is known as the father of modern physics?", "A) Niels Bohr", "B) Max Planck", "C) Albert Einstein", "D) Richard Feynman", "Albert Einstein"],
    ["Which artist painted 'The Starry Night'?", "A) Pablo Picasso", "B) Claude Monet", "C) Vincent van Gogh", "D) Salvador Dalí", "Vincent van Gogh"],
    ["What is the currency of Switzerland?", "A) Euro", "B) Swiss Franc", "C) Dollar", "D) Pound", "Swiss Franc"],
    ["Which Shakespeare play features Rosencrantz and Guildenstern?", "A) Macbeth", "B) Hamlet", "C) Othello", "D) King Lear", "Hamlet"],
    ["Who was the first man to reach the South Pole?", "A) Robert Scott", "B) Roald Amundsen", "C) Ernest Shackleton", "D) Edmund Hillary", "Roald Amundsen"],
    ["Which element is represented by the symbol 'Pb'?", "A) Platinum", "B) Lead", "C) Palladium", "D) Polonium", "Lead"],
    ["What is the name of the highest mountain in Africa?", "A) Mount Kenya", "B) Mount Elgon", "C) Kilimanjaro", "D) Atlas Mountains", "Kilimanjaro"],
    ["In which year did the Berlin Wall fall?", "A) 1987", "B) 1989", "C) 1991", "D) 1993", "1989"],
    ["What is the most abundant element in the universe?", "A) Helium", "B) Oxygen", "C) Hydrogen", "D) Carbon", "Hydrogen"],
    ["Which language has the most native speakers?", "A) English", "B) Spanish", "C) Mandarin Chinese", "D) Hindi", "Mandarin Chinese"],
    ["Who painted 'Guernica'?", "A) Pablo Picasso", "B) Diego Rivera", "C) Salvador Dalí", "D) Frida Kahlo", "Pablo Picasso"],
    ["What is the study of fungi called?", "A) Botany", "B) Zoology", "C) Mycology", "D) Ecology", "Mycology"],
    ["Which planet is known as the 'Morning Star'?", "A) Mars", "B) Venus", "C) Mercury", "D) Saturn", "Venus"]
]

Level_8 = [
    ["Which mathematician proved the unsolvability of the quintic equation?", "A) Évariste Galois", "B) Niels Henrik Abel", "C) Carl Friedrich Gauss", "D) Leonhard Euler", "Niels Henrik Abel"],
    ["Which theory explains the origin of the universe from a singular point?", "A) Steady State Theory", "B) Big Bang Theory", "C) Inflationary Theory", "D) Oscillating Universe Theory", "Big Bang Theory"],
    ["Who is considered the father of modern chemistry?", "A) Dmitri Mendeleev", "B) Antoine Lavoisier", "C) John Dalton", "D) Jöns Jacob Berzelius", "Antoine Lavoisier"],
    ["What is the main language used in international aviation?", "A) French", "B) Spanish", "C) English", "D) Russian", "English"],
    ["Which novel is a seminal work in the dystopian genre by George Orwell?", "A) Brave New World", "B) Fahrenheit 451", "C) 1984", "D) Animal Farm", "1984"],
    ["Who was the first woman to win a Nobel Prize?", "A) Rosalind Franklin", "B) Dorothy Hodgkin", "C) Marie Curie", "D) Irène Joliot-Curie", "Marie Curie"],
    ["What is the largest internal organ in the human body?", "A) Heart", "B) Liver", "C) Lung", "D) Kidney", "Liver"],
    ["Which element has the highest melting point?", "A) Iron", "B) Tungsten", "C) Carbon", "D) Osmium", "Tungsten"],
    ["Which continent has the most countries?", "A) Asia", "B) Africa", "C) Europe", "D) South America", "Africa"],
    ["What is the second most spoken language in the world?", "A) Spanish", "B) English", "C) Hindi", "D) Arabic", "Spanish"],
    ["Who wrote 'The Republic'?", "A) Socrates", "B) Plato", "C) Aristotle", "D) Cicero", "Plato"],
    ["Which battle is considered the turning point of the American Civil War?", "A) Battle of Antietam", "B) Battle of Gettysburg", "C) Battle of Chancellorsville", "D) Battle of Shiloh", "Battle of Gettysburg"],
    ["What is the primary function of ribosomes?", "A) Energy production", "B) Protein synthesis", "C) Lipid metabolism", "D) DNA replication", "Protein synthesis"],
    ["Which planet is known for its retrograde rotation?", "A) Mars", "B) Venus", "C) Jupiter", "D) Saturn", "Venus"],
    ["What is the chemical symbol for tungsten?", "A) Tu", "B) Tg", "C) W", "D) Tn", "W"],
    ["Who is the author of 'Crime and Punishment'?", "A) Leo Tolstoy", "B) Fyodor Dostoevsky", "C) Anton Chekhov", "D) Ivan Turgenev", "Fyodor Dostoevsky"],
    ["Which country is home to the ancient city of Petra?", "A) Egypt", "B) Jordan", "C) Lebanon", "D) Syria", "Jordan"],
    ["What is the largest species of shark?", "A) Great White Shark", "B) Hammerhead Shark", "C) Whale Shark", "D) Tiger Shark", "Whale Shark"],
    ["Who invented the printing press?", "A) Leonardo da Vinci", "B) Johannes Gutenberg", "C) Benjamin Franklin", "D) Thomas Edison", "Johannes Gutenberg"],
    ["Which instrument measures the pH level of a solution?", "A) Spectrophotometer", "B) pH meter", "C) Thermometer", "D) Barometer", "pH meter"],
    ["What is the capital of Mongolia?", "A) Ulaanbaatar", "B) Astana", "C) Tashkent", "D) Bishkek", "Ulaanbaatar"],
    ["Which metal is liquid at room temperature?", "A) Lead", "B) Gallium", "C) Mercury", "D) Sodium", "Mercury"],
    ["Who was the first president of the United States?", "A) Thomas Jefferson", "B) Abraham Lincoln", "C) George Washington", "D) John Adams", "George Washington"],
    ["Which vitamin is essential for blood clotting?", "A) Vitamin C", "B) Vitamin D", "C) Vitamin K", "D) Vitamin B12", "Vitamin K"],
    ["What is the capital of Finland?", "A) Oslo", "B) Helsinki", "C) Stockholm", "D) Copenhagen", "Helsinki"]
]

Level_9 = [
    ["Who developed the theory of evolution by natural selection?", "A) Jean-Baptiste Lamarck", "B) Charles Darwin", "C) Alfred Russel Wallace", "D) Gregor Mendel", "Charles Darwin"],
    ["What is Schrödinger's famous thought experiment involving a cat called?", "A) Schrödinger's Paradox", "B) Quantum Cat", "C) Schrödinger's Cat", "D) Feline Uncertainty", "Schrödinger's Cat"],
    ["Which ancient empire was ruled by Cyrus the Great?", "A) Roman Empire", "B) Achaemenid Empire", "C) Ottoman Empire", "D) Macedonian Empire", "Achaemenid Empire"],
    ["What is the term for animals that are active during twilight?", "A) Nocturnal", "B) Diurnal", "C) Crepuscular", "D) Vespertine", "Crepuscular"],
    ["Who composed the opera 'The Marriage of Figaro'?", "A) Giuseppe Verdi", "B) Richard Wagner", "C) Wolfgang Amadeus Mozart", "D) Gioachino Rossini", "Wolfgang Amadeus Mozart"],
    ["What is the rarest blood type in the world?", "A) O-negative", "B) AB-negative", "C) B-negative", "D) AB-positive", "AB-negative"],
    ["Which philosopher wrote 'Being and Time'?", "A) Jean-Paul Sartre", "B) Martin Heidegger", "C) Friedrich Nietzsche", "D) Søren Kierkegaard", "Martin Heidegger"],
    ["What is the main component of the Sun?", "A) Helium", "B) Carbon", "C) Hydrogen", "D) Oxygen", "Hydrogen"],
    ["In which year were the first modern Olympic Games held?", "A) 1896", "B) 1900", "C) 1888", "D) 1912", "1896"],
    ["Which economic principle describes a market with a single seller?", "A) Oligopoly", "B) Monopoly", "C) Duopoly", "D) Perfect Competition", "Monopoly"],
    ["Who is the Greek god of dreams?", "A) Hypnos", "B) Morpheus", "C) Phobos", "D) Thanatos", "Morpheus"],
    ["Which scientist introduced the concept of 'tabula rasa'?", "A) John Locke", "B) David Hume", "C) Immanuel Kant", "D) René Descartes", "John Locke"],
    ["What is the currency of Poland?", "A) Euro", "B) Zloty", "C) Forint", "D) Koruna", "Zloty"],
    ["Who discovered the law of electromagnetic induction?", "A) James Clerk Maxwell", "B) Michael Faraday", "C) Heinrich Hertz", "D) André-Marie Ampère", "Michael Faraday"],
    ["Which element is named after a planet?", "A) Neptunium", "B) Uranium", "C) Plutonium", "D) Mercury", "Uranium"],
    ["What is the study of the Earth's physical structure called?", "A) Geography", "B) Meteorology", "C) Geology", "D) Astronomy", "Geology"],
    ["Which book is often considered the first work of science fiction?", "A) 20,000 Leagues Under the Seas", "B) Frankenstein", "C) The Time Machine", "D) Journey to the Center of the Earth", "Frankenstein"],
    ["Who painted 'The Persistence of Memory'?", "A) René Magritte", "B) Salvador Dalí", "C) Pablo Picasso", "D) Claude Monet", "Salvador Dalí"],
    ["Which is the only mammal capable of true flight?", "A) Flying Squirrel", "B) Bat", "C) Colugo", "D) Sugar Glider", "Bat"],
    ["Who is considered the father of modern economics?", "A) Karl Marx", "B) John Maynard Keynes", "C) Adam Smith", "D) Milton Friedman", "Adam Smith"],
    ["What is the name of the largest moon of Saturn?", "A) Ganymede", "B) Titan", "C) Callisto", "D) Europa", "Titan"],
    ["Which element has the highest atomic number in the periodic table?", "A) Uranium", "B) Plutonium", "C) Oganesson", "D) Californium", "Oganesson"],
    ["Which structure is known as the longest wall in the world?", "A) Berlin Wall", "B) Hadrian's Wall", "C) Great Wall of China", "D) Western Wall", "Great Wall of China"],
    ["What is the rarest naturally occurring element in the Earth's crust?", "A) Francium", "B) Astatine", "C) Promethium", "D) Technetium", "Astatine"],
    ["Who was the first person to propose the heliocentric model of the solar system?", "A) Ptolemy", "B) Copernicus", "C) Aristarchus of Samos", "D) Galileo Galilei", "Aristarchus of Samos"]
]

Level_10 = [
    ["Which physicist is known for formulating the Uncertainty Principle?", "A) Niels Bohr", "B) Werner Heisenberg", "C) Erwin Schrödinger", "D) Max Planck", "Werner Heisenberg"],
    ["What is the Riemann Hypothesis concerned with?", "A) Distribution of prime numbers", "B) Convergence of infinite series", "C) Topology of manifolds", "D) Behavior of fractals", "Distribution of prime numbers"],
    ["Which philosopher is famous for the statement 'I think, therefore I am'?", "A) Immanuel Kant", "B) René Descartes", "C) Friedrich Nietzsche", "D) Jean-Paul Sartre", "René Descartes"],
    ["What is the most abundant isotope of carbon?", "A) Carbon-12", "B) Carbon-13", "C) Carbon-14", "D) Carbon-10", "Carbon-12"],
    ["Which law states that the pressure and volume of a gas have an inverse relationship?", "A) Charles' Law", "B) Boyle's Law", "C) Gay-Lussac's Law", "D) Avogadro's Law", "Boyle's Law"],
    ["Who proposed the Many-Worlds Interpretation of quantum mechanics?", "A) Niels Bohr", "B) Hugh Everett III", "C) Erwin Schrödinger", "D) Max Born", "Hugh Everett III"],
    ["What is the mathematical constant representing the ratio of a circle's circumference to its diameter?", "A) e", "B) Phi", "C) Pi", "D) Gamma", "Pi"],
    ["In quantum mechanics, what does the term 'superposition' refer to?", "A) A particle existing in a single state", "B) A particle existing in multiple states simultaneously", "C) The collapse of the wavefunction", "D) Quantum entanglement", "A particle existing in multiple states simultaneously"],
    ["Which branch of mathematics deals with the properties and relations of integers?", "A) Algebra", "B) Calculus", "C) Number Theory", "D) Topology", "Number Theory"],
    ["What is the principle of mathematical induction used for?", "A) Solving differential equations", "B) Proving statements for all natural numbers", "C) Calculating integrals", "D) Analyzing algorithms", "Proving statements for all natural numbers"],
    ["Who is credited with the development of modern set theory?", "A) Bertrand Russell", "B) Georg Cantor", "C) Kurt Gödel", "D) Alfred Tarski", "Georg Cantor"],
    ["What does Gödel's Incompleteness Theorem state?", "A) Every mathematical truth can be proven", "B) Some truths cannot be proven within a formal system", "C) All formal systems are complete", "D) Mathematics is inconsistent", "Some truths cannot be proven within a formal system"],
    ["Which paradox involves a statement that declares itself to be false?", "A) Russell's Paradox", "B) Zeno's Paradox", "C) The Liar Paradox", "D) The Paradox of Value", "The Liar Paradox"],
    ["What is the concept of 'dark matter' used to explain?", "A) The expansion of the universe", "B) Gravitational effects in galaxies", "C) The behavior of black holes", "D) The cosmic microwave background", "Gravitational effects in galaxies"],
    ["Who introduced the concept of the 'block universe' in relation to time?", "A) Albert Einstein", "B) Hermann Minkowski", "C) Stephen Hawking", "D) Roger Penrose", "Hermann Minkowski"],
    ["Which field studies how small changes can lead to large differences in complex systems?", "A) Chaos Theory", "B) Systems Biology", "C) Cybernetics", "D) Fractal Geometry", "Chaos Theory"],
    ["What is the phenomenon called when light is bent around a massive object?", "A) Refraction", "B) Diffraction", "C) Gravitational Lensing", "D) Polarization", "Gravitational Lensing"],
    ["Which mathematician solved Fermat's Last Theorem?", "A) Pierre de Fermat", "B) Andrew Wiles", "C) Leonhard Euler", "D) Carl Friedrich Gauss", "Andrew Wiles"],
    ["What is the hypothetical particle that mediates the force of gravity called?", "A) Photon", "B) Gluon", "C) Graviton", "D) Neutrino", "Graviton"],
    ["Which scientific theory describes the behavior of particles at the smallest scales?", "A) Relativity", "B) Classical Mechanics", "C) Quantum Mechanics", "D) Thermodynamics", "Quantum Mechanics"],
    ["What is the Heisenberg Uncertainty Principle fundamentally about?", "A) Limitations in measuring certain pairs of physical properties", "B) The speed of light as a constant", "C) The dual nature of matter", "D) The conservation of energy", "Limitations in measuring certain pairs of physical properties"],
    ["Which algorithm is used to find the shortest path in a graph?", "A) Prim's Algorithm", "B) Kruskal's Algorithm", "C) Dijkstra's Algorithm", "D) Bellman-Ford Algorithm", "Dijkstra's Algorithm"],
    ["What is the study of the structure and behavior of complex networks called?", "A) Graph Theory", "B) Network Science", "C) Systems Theory", "D) Cybernetics", "Network Science"],
    ["Which conjecture states that every even integer greater than 2 can be expressed as the sum of two primes?", "A) Goldbach's Conjecture", "B) Twin Prime Conjecture", "C) Collatz Conjecture", "D) Riemann Conjecture", "Goldbach's Conjecture"],
    ["Which branch of physics deals with subatomic particles and their interactions?", "A) Thermodynamics", "B) Electrodynamics", "C) Particle Physics", "D) Astrophysics", "Particle Physics"]
]
